<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="966391" started-at="2015-09-30T00:22:41Z" finished-at="2015-09-30T00:38:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="966391" started-at="2015-09-30T00:22:41Z" finished-at="2015-09-30T00:38:47Z">
      <class name="com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="beforeClass" is-config="true" duration-ms="20" started-at="2015-09-29T20:22:41Z" finished-at="2015-09-29T20:22:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="beforeMethod" is-config="true" duration-ms="3464" started-at="2015-09-29T20:22:41Z" finished-at="2015-09-29T20:22:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TestCase1()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="TestCase1" duration-ms="245097" started-at="2015-09-29T20:22:45Z" finished-at="2015-09-29T20:26:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests.TestCase1(WalmartLabs_HWAssignment_Tests.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="afterMethod" is-config="true" duration-ms="990" started-at="2015-09-29T20:26:50Z" finished-at="2015-09-29T20:26:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="beforeMethod" is-config="true" duration-ms="3366" started-at="2015-09-29T20:26:51Z" finished-at="2015-09-29T20:26:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TestCase2()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="TestCase2" duration-ms="191036" started-at="2015-09-29T20:26:54Z" finished-at="2015-09-29T20:30:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests.TestCase2(WalmartLabs_HWAssignment_Tests.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase2 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="afterMethod" is-config="true" duration-ms="2562" started-at="2015-09-29T20:30:05Z" finished-at="2015-09-29T20:30:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="beforeMethod" is-config="true" duration-ms="4396" started-at="2015-09-29T20:30:08Z" finished-at="2015-09-29T20:30:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TestCase3()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="TestCase3" duration-ms="203693" started-at="2015-09-29T20:30:12Z" finished-at="2015-09-29T20:33:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [3]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests.TestCase3(WalmartLabs_HWAssignment_Tests.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase3 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="afterMethod" is-config="true" duration-ms="1790" started-at="2015-09-29T20:33:36Z" finished-at="2015-09-29T20:33:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="beforeMethod" is-config="true" duration-ms="4453" started-at="2015-09-29T20:33:38Z" finished-at="2015-09-29T20:33:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TestCase4()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="TestCase4" duration-ms="210339" started-at="2015-09-29T20:33:42Z" finished-at="2015-09-29T20:37:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests.TestCase4(WalmartLabs_HWAssignment_Tests.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase4 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="afterMethod" is-config="true" duration-ms="2118" started-at="2015-09-29T20:37:12Z" finished-at="2015-09-29T20:37:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="beforeMethod" is-config="true" duration-ms="3421" started-at="2015-09-29T20:37:14Z" finished-at="2015-09-29T20:37:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TestCase5()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="TestCase5" duration-ms="87704" started-at="2015-09-29T20:37:18Z" finished-at="2015-09-29T20:38:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase5 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests@6adca536]" name="afterMethod" is-config="true" duration-ms="1823" started-at="2015-09-29T20:38:46Z" finished-at="2015-09-29T20:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.WalmartLabs.HomeWorkAssignment.WalmartLabs_HWAssignment_Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
